backend:
  name: git-gateway
  branch: main # or your default branch

# Media files will be stored here
media_folder: "public/images/uploads"
public_folder: "/images/uploads"

# Collections of content
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "src/data/home.json"
        fields:
          - {label: "Hero Title", name: "heroTitle", widget: "string"}
          - {label: "Hero Description", name: "heroDescription", widget: "text"}
          - {label: "About Title", name: "aboutTitle", widget: "string"}
          - {label: "About Description", name: "aboutDescription", widget: "markdown"}
          - {label: "Skills", name: "skills", widget: "list", fields: [
              {label: "Skill Name", name: "name", widget: "string"},
              {label: "Skill Level", name: "level", widget: "number", min: 1, max: 100}
            ]}
          - {label: "Projects", name: "projects", widget: "list", fields: [
              {label: "Project Title", name: "title", widget: "string"},
              {label: "Project Description", name: "description", widget: "markdown"},
              {label: "Project Image", name: "image", widget: "image"},
              {label: "Project Link", name: "link", widget: "string", required: false}
            ]}
          - {label: "Contact Title", name: "contactTitle", widget: "string"}
          - {label: "Contact Description", name: "contactDescription", widget: "text"}
          - {label: "Social Links", name: "socialLinks", widget: "list", fields: [
              {label: "Platform", name: "platform", widget: "string"},
              {label: "URL", name: "url", widget: "string"}
            ]}

  - name: "media"
    label: "Media Gallery"
    file: "src/data/mediaItems.json"
    fields:
      - {label: "Media Items", name: "items", widget: "list", fields: [
          {label: "Title", name: "title", widget: "string"},
          {label: "Type", name: "type", widget: "select", options: ["youtube", "linkedin", "twitter", "article", "document"]},
          {label: "URL", name: "url", widget: "string"},
          {label: "Video ID", name: "videoId", widget: "string", required: false},
          {label: "Embed URL", name: "embedUrl", widget: "string", required: false},
          {label: "Thumbnail", name: "thumbnail", widget: "image", required: false}
        ]} 